name: synthrad-gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scikit-image
  - nibabel
  - pydicom
  - simpleitk
  - pip
  - pip:
      - monai==0.7.0
      - einops==0.3.2
      - timm==0.4.12
      - ml-collections==0.1.0
      - medpy==0.4.0
      - medutils==0.1.15
      - torchio==0.18.57
      - torchsummary==1.5.1
      - volumentations-3d==1.0.3
      - seg-metrics==1.0.17
      - tqdm
      - seaborn
      - opencv-python
      - natsort
